name: The Pinhole Gallery
favicon: null
layout_spectrum: 0.5662866809871048
typography_spectrum: 0.7941538006998599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5452939323149621
  lightness: 0.2706295750103891
  saturation: 0.09307057270780206
  rhythmicContrast: 0.6221442914102226
purpose: []
